/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:dfb543a4-863b-418d-99c0-f0fa45c63dd3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_Nht3a5ltD",
    "aws_user_pools_web_client_id": "7u0mgdtmanueri3upjjgstldun",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://373hu7n43nbv3hi4b7xgdrfsuq.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2unptvmvrngjdozam5ou47djvi",
    "aws_user_files_s3_bucket": "rapiddevch37431f51ead3f4aafa57b4a97beebe72b123419-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
